// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: survey.proto

package survey

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SuveyService_GetAuthorization_FullMethodName = "/survey.SuveyService/GetAuthorization"
)

// SuveyServiceClient is the client API for SuveyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SuveyServiceClient interface {
	GetAuthorization(ctx context.Context, in *GetAuthorizationInput, opts ...grpc.CallOption) (*GetAuthorizationOutput, error)
}

type suveyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSuveyServiceClient(cc grpc.ClientConnInterface) SuveyServiceClient {
	return &suveyServiceClient{cc}
}

func (c *suveyServiceClient) GetAuthorization(ctx context.Context, in *GetAuthorizationInput, opts ...grpc.CallOption) (*GetAuthorizationOutput, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAuthorizationOutput)
	err := c.cc.Invoke(ctx, SuveyService_GetAuthorization_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SuveyServiceServer is the server API for SuveyService service.
// All implementations must embed UnimplementedSuveyServiceServer
// for forward compatibility.
type SuveyServiceServer interface {
	GetAuthorization(context.Context, *GetAuthorizationInput) (*GetAuthorizationOutput, error)
	mustEmbedUnimplementedSuveyServiceServer()
}

// UnimplementedSuveyServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSuveyServiceServer struct{}

func (UnimplementedSuveyServiceServer) GetAuthorization(context.Context, *GetAuthorizationInput) (*GetAuthorizationOutput, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAuthorization not implemented")
}
func (UnimplementedSuveyServiceServer) mustEmbedUnimplementedSuveyServiceServer() {}
func (UnimplementedSuveyServiceServer) testEmbeddedByValue()                      {}

// UnsafeSuveyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SuveyServiceServer will
// result in compilation errors.
type UnsafeSuveyServiceServer interface {
	mustEmbedUnimplementedSuveyServiceServer()
}

func RegisterSuveyServiceServer(s grpc.ServiceRegistrar, srv SuveyServiceServer) {
	// If the following call pancis, it indicates UnimplementedSuveyServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SuveyService_ServiceDesc, srv)
}

func _SuveyService_GetAuthorization_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAuthorizationInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SuveyServiceServer).GetAuthorization(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SuveyService_GetAuthorization_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SuveyServiceServer).GetAuthorization(ctx, req.(*GetAuthorizationInput))
	}
	return interceptor(ctx, in, info, handler)
}

// SuveyService_ServiceDesc is the grpc.ServiceDesc for SuveyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SuveyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "survey.SuveyService",
	HandlerType: (*SuveyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAuthorization",
			Handler:    _SuveyService_GetAuthorization_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "survey.proto",
}
