server:
  scheme: "http"
  host: "0.0.0.0"
  port: 8080
  portCompressMicroservice: 8091
  frontURI: "http://172.28.166.156:8080/"
  mediadir: "media/UnCompressed/"
  auth_host: auth_microservice
  auth_port: 8000
  csrf_secret: "rand string" # 16, 24 or 32 bytes string allowed!

database:
  host: "192.168.77.130"
  port: 5432
  user: "postgres"
  password: "passIMO"
  schema: "public"
  db_name: "postgres"
  ssl_mode: "disable"
  # conn_timeout: 60s

auth_microservice:
  server:
    scheme: "http"
    host: "192.168.77.130"
    port: 8091
    metrics_port: 8000
  database:
    host: "192.168.77.130"
    port: 6379
    user: user
    password: 1234123412341234

compress_microservice:
  server:
    scheme: "http"
    host: "192.168.77.130"
    port: 8071
<<<<<<< HEAD
    metrics_port: 8000
=======
>>>>>>> dev
  CompressedMediaDir: "media/Compressed/"
