server:
  scheme: "http"
  host: "192.168.77.130"
  port: 8090
  frontURI: "http://192.168.77.130:8000"
  mediadir: "media/UnCompressed/"
  

database:
  host: "192.168.77.130"
  port: 5432
  user: "postgres"
  password: "passIMO"
  schema: "public"
  db_name: "postgres"
  ssl_mode: "disable"
  # conn_timeout: 60s

auth_microservice:
  server:
    scheme: "http"
    host: "192.168.77.130"
    port: 8091
  database:
    host: "192.168.77.130"
    port: 6379
    password: "passIMO"

compress_microservice:
  server:
    scheme: "http"
    host: "192.168.77.130"
    port: 8071
  CompressedMediaDir: "media/Compressed/"

notifications_microservice:
  server:
    scheme: "http"
    host: "192.168.77.130"
    port: 8061