global:
  scrape_interval: 10m

scrape_configs:
  - job_name: node
    static_configs:
      - targets: ['node_exporter:9100']

  - job_name: main-service
    static_configs:
      - targets: ['main_service:8001']

  - job_name: auth-microservice
    static_configs:
      - targets: ['auth_microservice:8000']

  - job_name: compress-microservice
    static_configs:
      - targets: ['compress_microservice:8000']
