basePath: /api/v1
definitions:
  dto.JSONApplicantRegistrationForm:
    properties:
      birthDate:
        type: string
      email:
        type: string
      firstName:
        type: string
      lastName:
        type: string
      password:
        type: string
    type: object
  dto.JSONEmployerRegistrationForm:
    properties:
      companyDescription:
        type: string
      companyName:
        type: string
      companyWebsite:
        type: string
      email:
        type: string
      firstName:
        type: string
      lastName:
        type: string
      password:
        type: string
      position:
        type: string
    type: object
  dto.JSONGetApplicantProfile:
    properties:
      avatar:
        type: string
      birthDate:
        type: string
      city:
        type: string
      contacts:
        type: string
      education:
        type: string
      firstName:
        type: string
      id:
        type: integer
      lastName:
        type: string
    type: object
  dto.JSONResponse:
    properties:
      body: {}
      error:
        type: string
      statusCode:
        type: integer
    type: object
  dto.JSONUser:
    properties:
      id:
        type: integer
      userType:
        type: string
    type: object
host: 127.0.0.1:8080
info:
  contact:
    name: Olgmuzalev13
    url: https://github.com/Olgmuzalev13
  title: Î¼Art's API
  version: "1.0"
paths:
  /CVs:
    get:
      description: Accepts offset and number of CVs with id >= offset. Returns CVs
      parameters:
      - description: offset
        in: query
        name: offset
        required: true
        type: integer
      - description: num
        in: query
        name: num
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "405":
          description: Method Not Allowed
        "500":
          description: Internal Server Error
      summary: Gets list of CVs
      tags:
      - CVs
  /applicant/profile/{id}:
    get:
      consumes:
      - application/json
      description: Get applicant profile by ID
      parameters:
      - description: Applicant ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.JSONGetApplicantProfile'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.JSONResponse'
      summary: Get applicant profile
      tags:
      - Applicant
  /registration/applicant/:
    post:
      consumes:
      - application/json
      description: '-'
      parameters:
      - description: Example
        in: body
        name: example
        required: true
        schema:
          $ref: '#/definitions/dto.JSONApplicantRegistrationForm'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.JSONUser'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.JSONResponse'
      summary: Creates a new user as a applicant
      tags:
      - Registration
  /registration/employer/:
    post:
      consumes:
      - application/json
      description: '-'
      parameters:
      - description: Example
        in: body
        name: example
        required: true
        schema:
          $ref: '#/definitions/dto.JSONEmployerRegistrationForm'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.JSONUser'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.JSONResponse'
      summary: Creates a new user as a employer
      tags:
      - Registration
  /vacancies:
    get:
      description: Accepts offset and number of vacancies with id >= offset. Returns
        vacancies
      parameters:
      - description: offset
        in: query
        name: offset
        required: true
        type: integer
      - description: num
        in: query
        name: num
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "405":
          description: Method Not Allowed
        "500":
          description: Internal Server Error
      summary: Gets list of vacancies
      tags:
      - Vacancies
swagger: "2.0"
