name: CD workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - dev
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Executing remote ssh connection
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER_NAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            sudo rm -rf ~/CD
            mkdir ~/CD
            cd ~/CD
            git clone https://github.com/go-park-mail-ru/2024_2_VKatuny.git .
            cp ~/configs/conf.yml ./configs/
            cp ~/configs/tern.conf ./db/migrations/
            cp ~/configs/prometheus.yml ./configs/
            cp ~/configs/.env ./
            sudo docker compose -f ./all-services-compose.yaml down
            sudo docker compose -f ./all-services-compose.yaml build
            sudo docker compose -f ./all-services-compose.yaml up -d
            cd ./db/migrations/
            ~/go/bin/tern migrate
