name: Generate API specification
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  generate-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23.x"
      - name: Install dependencies
        run: |
          go install github.com/swaggo/swag/cmd/swag@latest
          go get ./...
      - name: Generate API specification
        run: |
          swag init --generalInfo ./cmd/app/main.go --output api/ --pd
      - name: Commit API
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add api
          git commit -m "chore: update api"
