name: Lint source files
on: 
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.x'
      - name: Install Linter
        run: go install github.com/mgechev/revive@latest
      - name: Lint files
        run: make lint
  
  
